[package]
name = "strip-or-replace-data-file-index-file-paths"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.5", features = ["derive"] }
csv = "1.3"
rayon = "1.10"
glob = "0.3"
anyhow = "1.0"